### ISSUE TITLE
Scheduled cache purging based on LastPull attribute is not executed.

### ISSUE THREAD

**Issue by bpeckNR** [newrelic/newrelic-pcf-nozzle-tile#17]
## Description

The switch case statement in cfclient/cfapps/cache.go that checks the LastPull time for each application in the cache to remove old entries does not get executed. Only UpdateInstances and adding new applications to the cache ever get executed.

This can cause: 
-  If an application in the cache no longer exists, the nozzle will continue to attempt to update instance details for that application and trigger HTTP 404 errors.
-  If the rate limiter causes the initial FetchApp calls to timeout, an app.name attribute can get stuck with the value of WAITING FOR DATA. Since FetchApp is only called for new applications and the cached applications are never removed, the WAITING FOR DATA app.name would never be updated.
- If VCAP details for an existing application to enable multi-account event router are updated (RPM account ID / Insights insert key) those changes would not take effect until the nozzle is restarted.

This behavior

## Steps to Reproduce

A logging statement can be added to the case statement for time.NewTicker(cacheDuration * time.Minute).C to show that the logic isn't executed.

## Expected Behavior

The scheduled cache purge should be corrected so that cached application data is only used for ~30 minutes and then FetchApp will be called to get updated application data when a ContainerMetric or LogMessage envelope type is received for that application GUID again.

**Comment by gsanchezgavier** [comment]
Thank you Brian for reporting this issue, I just add it to our backlog

**Comment by shahramk** [comment]
Hello @gsanchezgavier - a zendesk ticket was added for record keeping, so the field engineers could be notified. ticket#: 399708 (https://newrelic.zendesk.com/agent/tickets/399708)

**Comment by AndrewConacher** [comment]
Hi team checking in here is there an ETA. Is this WAITING ON DATA noise that we can safely filter out in the  dashboards or is it pointing to bigger issue?

**Comment by paologallinaharbur** [comment]
In the past days we have been testing a fix to this issue that will be included in the next release. However I do not have any ETA, I will follow up here when I have updates.

**Comment by paologallinaharbur** [comment]
@AndrewConacher 
 By the way the label `WAITING ON DATA` is there if no info has been found regarding an app id. Usually at startup time there are many samples having that name, further on their number should reduce, however there will be always a small number of samples connected to apps not resolved yet.
This fix will clean properly the cache from old data and will help reducing the size of such samples
