### ISSUE TITLE
Misconfiguration in Insights authentication log fload

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/newrelic-pcf-nozzle-tile#19]
In case the authentication fails multiple logs are created, out for each sample and not mechanism is in place to reduce the speed as the post failed.

```xxxxxxxxxxx 1 Wed May 06 2020 14:10:24.702 time="2020-05-06T18:10:24Z" level=error msg="Failed to send insights events [1/3]. Will retry. Error: Insights Post: : bad response from Insights: 403 \n\t{}"```

Expected behaviour:
The logs are shown, but the amount between each event is reasonable.

**Comment by gsanchezgavier** [comment]
#20 added a check of the key and stop the nozzle in case of a invalid key. This will help to find out the problem from the logs when the key is not valid
