### ISSUE TITLE
Monitoring of NewRelic firehose nozzle

### ISSUE THREAD

**Issue by stdesantiago** [newrelic/newrelic-pcf-nozzle-tile#2]
How would you go about monitoring the NewRelic firehose nozzle in the event that it crashes or hangs and does not restart?  We have had a couple instances where when we lose networking our monitoring doesn't work and we have to go in and restart.

**Comment by shahramk** [comment]
@stdesantiago - apologies for not attending this repo's issues for some time. 
the newer releases of the nozzle have healthcheck, and cloud controller watches the instances.
 if they do not respond within reasonable amount of time, they are restarted.

which version of the nozzle are you using?

**Comment by shahramk** [comment]
question answered
