### ISSUE TITLE
Including spaces in nrf_enabled_envelope_types leads to dropped data types

### ISSUE THREAD

**Issue by bpeckNR** [newrelic/newrelic-pcf-nozzle-tile#33]
## Description
Including spaces in a comma or pipe separated value for nrf_enabled_envelope_types causes those envelope types to not be sent to the New Relic platform. Ideally we should make this case insensitive as well.

## Expected Behavior
Ability to include spaces in the configuration and potentially not match the expected case without impacting customers.

## Steps to Reproduce
Set nrf_enabled_envelope_types to ContainerMetric, CounterEvent, ValueMetric and only ContainerMetric will be reported.

**Comment by bpeckNR** [comment]
I'll submit a PR for review shortly that fixes this issue.

**Comment by gsanchezgavier** [comment]
@bpeckNR  I checked the example in the manifest and the docs and the configuration accepts pipe separated values 

https://github.com/newrelic/newrelic-pcf-nozzle-tile/blob/master/manifest.yml.sample#L63

we should maintain that for backward compatibility too.
