### ISSUE TITLE
Correct EU API endpoints configuration. Allow separate custom configuration of Both Logs and Event API endpoint.

### ISSUE THREAD

**Issue by stephencrowley** [newrelic/newrelic-pcf-nozzle-tile#40]
## Description
 Default EU configuration (UI) does not send Event data to EU New Relic Accounts due to misconfiguration in [newrelic-client-go](https://github.com/newrelic/newrelic-client-go/issues/663)

This can be fixed by setting a "Custom Insights URL" but this also overrides the Logging API endpoint causing logging data to not be sent.
https://github.com/newrelic/newrelic-pcf-nozzle-tile/blob/master/newrelic/nrclients/nrclients.go#L192-L193

## Expected Behavior
[NOTE]: #  When selecting EU as account region that the data be sent to the EU.
When Custom Insights URL is chosen that this only configures the Event Endpoint URL and not both the Event and Logs endpoint.

## Additional context
I have opened a ticket to fix the default value for the New Relic Client API endpoint
https://github.com/newrelic/newrelic-client-go/issues/663

**Comment by gsanchezgavier** [comment]
Thank @stephencrowley for communicating the finding. I add this to our backlog.
