### ISSUE TITLE
Dashboard code is outdated

### ISSUE THREAD

**Issue by frank-martens** [newrelic/newrelic-pcf-nozzle-tile#51]
[NOTE]: # The JSON will not import into the new platform interface.

## Description
[NOTE]: When trying to copy and paste the JSON code for the dashboard, it is not compatible with new platform requirements

## Expected Behavior
[NOTE]: Import of JSON code to work

**Comment by davidgit** [comment]
Hi @frank-martens,

We appreciate you taking the time to bring this to our attention. We will redirect this bug internally.
