### ISSUE TITLE
Custom Attributes are not being sent via Firehose

### ISSUE THREAD

**Issue by KMontag42** [newrelic/newrelic-pcf-nozzle-tile#54]
SUPPORT TICKET ID: `500Ph000007dNFF`

We are having issues with data consistency with our newrelic firehose.

it seems like the firehose is not consistent with sending custom attributes for events.

example event from NR UI ( I have masked the values here for security, but assume each one does have a value ).
```
{
  "appId": ,
  "appName": "",
  "containerId": "",
  "daily_crawls":,
  "daily_errors": ,
  "date": "",
  "entityGuid": "",
  "host": "worker",
  "organization_id": "",
  "priority":,
  "products":,
  "realAgentId":,
  "retailer": "",
  "tags.account": "",
  "tags.accountId": "",
  "tags.trustedAccountId": "",
  "timestamp":,
  "weekly_crawls": ,
  "weekly_errors": 
},
```

example event JSON from firehose:
```
{
    "accountId":,
    "appName": "",
    "applicationId":,
    "containerId": "",
    "entityGuid": "",
    "eventType": "",
    "host": "",
    "nrNoWrite:customAttributes": 8,
    "organization_id": "",
    "priority": ,
    "realAgentId": ,
    "retailer": "",
    "tags.account": "",
    "tags.accountId": "",
    "tags.trustedAccountId": "",
    "timestamp": 
}
```

what is the `nrNoWrite:customAttributes` value? is it masking our custom attributes like `weekly_errors` ?

our understanding is that we are using a legacy NR firehose connection, and we are thinking this might be the cause of the issue.

is there documentation for this firehose? or potentially a more up to date code path we could use?

**Comment by jbeveland27** [comment]
Hey @KMontag42! Sorry for the delay in getting back to you. Could we get some additional info to help with this issue:
- Which version of Tanzu are you on?
- Which version of the Nozzle are you on?

> is there documentation for this firehose?

The main docs we have are located in the README of this repo. But we've also got some docs here: https://docs.newrelic.com/docs/more-integrations/cloudfoundry-integrations/vmware-tanzu-firehose-nozzle-integration/

**Comment by miransar** [comment]
Closing this ticket as this issue is not related to this repository, it looks like it's related to Kinesis Firehose, not Tanzu Firehose, same has been informed to support team so they can direct in the right direction. If you see this is related to Tanzu firehose, please reopen the issue. Thanks.
