### ISSUE TITLE
The nozzle v1.1.20 is calling /v2/apps with deprecated parameter inline-relations-depth

### ISSUE THREAD

**Issue by chenweienn** [newrelic/newrelic-pcf-nozzle-tile#6]
1. Customer deployed new relic nozzle tile downloaded from Pivotal (https://network.pivotal.io/products/nr-firehose-nozzle/).

2. The installed nozzle apps are polling CAPI once for every minute. 
`NOZZLE_APP_DETAIL_INTERVAL: 1`
The requests looks like:
"GET /v2/apps?inline-relations-depth=2&order-direction=asc&page=2&results-per-page=50

3. The parameter `inline-relations-depth` has been deprecated for a while. The use of this parameter will make the API call more expensive as explained by CAPI team:

> `inline-relations-depth` queries have been deprecated for a very long time due to performance issues like this. In particular, each time we add new features or database models, `inline-relations-depth` queries will now have to join (with or without an index!) those new models into each query.

> so as our database model grows more complex, those queries get more and more expensive.

Please consider to remove the use of this parameter.

Wayne
Pivotal Customer Support

**Comment by shahramk** [comment]
As we need to obtain org and space names and several other metrics, the alternative is to make extra CC API calls for each app, In this case it would be more expensive. 

Nozzle v1.1.22 and higher use Redis caching which requires only one of the instances to hit the cloud controller and decreases the CC API calls. 

Additionally in the upcoming release of the nozzle (2.x) the mechanism to obtain application metadata is handled differently and it has a rate limiter which prevents the nozzle from generating extra overhead for on cloud controller.
