### ISSUE TITLE
NR-App logging issue

### ISSUE THREAD

**Issue by farukhkhan87** [newrelic/newrelic-pcf-nozzle-tile#7]
After deploying NR-Firehose we noticed that our PCF-Metrics App "metrics-ingestor" started crashing with "Out of memory" errors. Looking at the NR-Firehose application (newrelic-firehose-nozzle-1.1.22) logs the reason seems to be pretty obvious as there is alot of junk data '//////' being logged non-stop which is causing the ingestor to crash. Below is the log message

value:\\\"sys.cfsb-1.gaig.com\\\" > logMessage:<message:\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\" message_type:OUT timestamp:1571687791461137400 app_id:\\\\\\\"379c2de7-22ac-4b82-92e5-26ca45bdbeeb\\\\\\\" source_type:\\\\\\\"APP/PROC/WEB\\\\\\\" source_instance:\\\\\\\"1\\\\\\\" > \\\" message_type:OUT timestamp:1571687794535489769 app_id:\\\"379c2de7-22ac-4b82-92e5-26ca45bdbeeb\\\" source_type:\\\"APP/PROC/WEB\\\" source_instance:\\\"0\\\" > \" message_type:OUT timestamp:1571687798423133705 app_id:\"379c2de7-22ac-4b82-92e5-26ca45bdbeeb\" source_type:\"APP/PROC/WEB\" source_instance:\"2\" > " message_type:OUT timestamp:1571687800953327629 app_id:"379c2de7-22ac-4b82-92e5-26ca45bdbeeb" source_type:"APP/PROC/WEB" source_instance:"0" >
2019-10-21T15:56:45.639-04:00 [APP/PROC/WEB/0] [OUT] \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

I wonder if anyone else has experienced similar issue? Even though the [Release Notes](https://docs.pivotal.io/partners/new-relic-nozzle/release-notes.html) for v1.1.21 mentioned the fix, we are seeing similar behavior both in v1.1.21 and v1.1.22. Thoughts?

**Comment by shahramk** [comment]
@farukhkhan123 Firehose nozzle 1.1.26 has been registered on PivNet and available for general access. Thank you for your help pinpointing the issue.
